// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web_Join.Models;

public partial class Assignment
{
    public int AID { get; set; }

    public int UserID { get; set; }

    public int TicketID { get; set; }

    public string Change { get; set; }

    public DateTime Assignmentdate { get; set; }

    public virtual Ticket Ticket { get; set; }

    public virtual User User { get; set; }
}