// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web_Join.Models;

public partial class Attachment
{
    public int ATID { get; set; }

    public int UserID { get; set; }

    public int TicketID { get; set; }

    public string Filepath { get; set; }

    public string Filename { get; set; }

    public int? Filesize { get; set; }

    public string Filetype { get; set; }

    public DateTime Uploadtime { get; set; }

    public virtual Ticket Ticket { get; set; }

    public virtual User User { get; set; }
}