// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web_Join.Models;

public partial class Notification
{
    public int NID { get; set; }

    public int UserID { get; set; }

    public int TicketID { get; set; }

    public string NotificationType { get; set; }

    public string Message { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsRead { get; set; }

    public virtual Ticket Ticket { get; set; }

    public virtual User User { get; set; }
}