// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web_Join.Models;

public partial class Ticket
{
    public int TID { get; set; }

    public int UserID { get; set; }

    public int StatusID { get; set; }

    public int PriorityID { get; set; }

    public int CategoryID { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateTime Createdate { get; set; }

    public DateTime? Duedate { get; set; }

    public virtual ICollection<Assignment> Assignments { get; set; } = new List<Assignment>();

    public virtual ICollection<Attachment> Attachments { get; set; } = new List<Attachment>();

    public virtual Category Category { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual ICollection<History> Histories { get; set; } = new List<History>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual Priority Priority { get; set; }

    public virtual Status Status { get; set; }

    public virtual User User { get; set; }
}